title: "Arnau's blog"
author: arnaualcazar
email: arnau@alcalleop.net
description: > # this means to ignore newlines until "baseurl:"
  Hi! Welcome to my blog. Here I will talk about things that interests me.
# social links
twitter_username: arnaualcazar # DO NOT include the @ character, or else the build will fail!
github_username:  arnaualcazar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 
